version: 2.1
orbs:
  prisma: prisma_cloud/devops_security@2.2.0
jobs:
  docker_build_and_save:
    executor: prisma/compute
    steps:
      - checkout
      - run: docker pull nginx
      - run: mkdir -p workspace
      - run: docker image
      - run: 'docker save nginx:latest -o workspace/image.tar'
      - persist_to_workspace:
          root: workspace
          paths:
            - image.tar
workflows:
  scan:
    jobs:
      - docker_build_and_save
      - prisma/image_scan:
          requires:
           - docker_build_and_save
          prisma_cloud_compute_url: 'https://157.52.255.14:8083'
          prisma_cloud_compute_user: demo
          prisma_cloud_compute_pass: PC_COMPUTE_PASS
          image: 'myrepo/myimage:tag'
          image_tar: image.tar
