version: 2
jobs:
  docker_build_and_save:
    machine: true
    working_directory: /tmp/twistlock-scan
    steps:
    - checkout
    - run:
        command: docker pull nginx
    - run:
        command: mkdir -p workspace
    - run:
        command: docker image
    - run:
        command: docker save nginx:latest -o workspace/image.tar
    - persist_to_workspace:
        root: workspace
        paths:
        - image.tar
  prisma/image_scan:
    machine: true
    working_directory: /tmp/twistlock-scan
    steps:
    - run:
        command: curl -k -u demo:${PC_COMPUTE_PASS} --output ./twistcli https://157.52.255.14:8083/api/v1/util/twistcli
    - run:
        command: sudo chmod a+x ./twistcli
    - attach_workspace:
        at: workspace
    - run:
        command: docker load -i workspace/image.tar
    - run:
        command: |
          result = $(./twistcli images scan --ci --details --address https://157.52.255.14:8083 -u demo -p ${PC_COMPUTE_PASS} nginx:latest])
          if [result == 1]; then exit 1; else
          exit 0;
          fi
    
workflows:
  scan:
    jobs:
    - docker_build_and_save
    - prisma/image_scan:
        requires:
        - docker_build_and_save
  version: 2
