version: 2
jobs:
  docker_build_and_save:
    machine: true
    working_directory: /tmp/twistlock-scan
    steps:
    - checkout
    - run:
        command: docker pull nginx
    - run:
        command: mkdir -p workspace
    - run:
        command: docker image
    - run:
        command: docker save nginx:latest -o workspace/image.tar
    - persist_to_workspace:
        root: workspace
        paths:
        - image.tar
  prisma/image_scan:
    machine: true
    working_directory: /tmp/twistlock-scan
    steps:
    - run:
        command: curl -k -u ${PC_COMPUTE_USER2}:${PC_COMPUTE_PASS2} --output ./twistcli ${PC_COMPUTE_URL2}/api/v1/util/twistcli
    - run:
        command: sudo chmod a+x ./twistcli
    - attach_workspace:
        at: workspace
    - run:
        command: docker load -i workspace/image.tar
    - run:
        command: ./twistcli images scan --ci --details --output-file scan_result.json --address ${PC_COMPUTE_URL2} -u ${PC_COMPUTE_USER2} -p ${PC_COMPUTE_PASS2} nginx:latest)
    - store_artifacts:
        path: scan_result.json
    
workflows:
  scan:
    jobs:
    - docker_build_and_save
    - prisma/image_scan:
        requires:
        - docker_build_and_save
  version: 2
